import Head from 'next/head'
import Image from 'next/image'
import ImageBox from '../Components/ImageBox'
import styles from '../styles/Home.module.css'
import { ErrorBoundary } from 'react-error-boundary'
import ErrorComponent from '../Components/ErrorComponent'
import HeroSection from '../Components/Hero'

export default function Home({images}) {
  return (
    <div >
      <Head>
        <title>StudyPaq Assignment Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HeroSection />
      </div>
      <ErrorBoundary FallbackComponent={ErrorComponent}>
        <main className='img-container'>
          {images.map(item=>{
            return <ImageBox item={item} key={item} /> 
          })}
        </main>
      </ErrorBoundary>

    
    </div>
  )
}
export async function getServerSideProps(){
  const res = await fetch('https://www.reddit.com/r/images/new.json?limit=30')
  const result = await res.json()
  const list = result.data.children
  const finalresult = []
  for(let i in list){
    if(list[i].data.thumbnail === 'nsfw'){
      finalresult.push(list[i].data.url_overridden_by_dest)
    }else{
      finalresult.push(list[i].data.thumbnail)
    }
  }
  return {
    props:{
      images:finalresult
    }
  }
}